general.import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
startup_mode = "Maximized"
dynamic_title = false

[font]
normal = {family = "JetBrains Mono"}
size = 14

[env]
TERM = "xterm-256color"
