ln -sf $PWD/.bashrc ~/.bashrc
ln -sf $PWD/.vimrc ~/.vimrc
ln -sf $PWD/.vim ~/
ln -sf $PWD/.tmux.conf ~/.tmux.conf
ln -sf $PWD/alacritty ~/.config/
ln -sf $PWD/.emacs ~/.emacs
ln -sf $PWD/.tmux.conf ~/
ln -sf $PWD/alacritty ~/.local/share/
ln -sf $PWD/colorschemes ~/.local/share/xfce4/terminal/
